
export const PREVIOUS_MONTH = "PREVIOUS_MONTH"
export const NEXT_MONTH = "NEXT_MONTH";
export const PREVIOUS_YEAR = "PREVIOUS_YEAR"
export const NEXT_YEAR = "NEXT_YEAR";

export const HOVER_DAY = "HOVER_DAY"

export const UPDATE_DAYOFF = "UPDATE_DAYOFF"
export const UPDATE_SCHEDULE = "UPDATE_SCHEDULE"
export const REMOVE_DAYOFF = "REMOVE_DAYOFF"
export const REMOVE_SCHEDULE = "REMOVE_SCHEDULE"


export const TOGGLE_MONDAY_SELECTION = "TOGGLE_MONDAY_SELECTION"

export const CLEAR_CHOSEN_MONDAYS = "CLEAR_CHOSEN_MONDAYS"

export const SET_COLOR = "SET_COLOR"

export const SET_DRAGGED_TYPE = "SET_DRAGGED_TYPE"


export const ADD_EMPLOYEE = "ADD_EMPLOYEE"
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE"